# ██╗      █████╗ ██╗   ██╗ ██████╗ ██╗   ██╗████████╗
# ██║     ██╔══██╗╚██╗ ██╔╝██╔═══██╗██║   ██║╚══██╔══╝
# ██║     ███████║ ╚████╔╝ ██║   ██║██║   ██║   ██║   
# ██║     ██╔══██║  ╚██╔╝  ██║   ██║██║   ██║   ██║   
# ███████╗██║  ██║   ██║   ╚██████╔╝╚██████╔╝   ██║   
# ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝  ╚═════╝    ╚═╝   
#-----------------------------------------------------



dwindle {
    preserve_split = true # You probably want this
    force_split = 0      # classic Hyprland snake tiling (no rigid 2-column pocket)
    smart_split = false
}

master {
    new_status = master
}